### ISSUE TITLE
send_receive_reply_CIMIdentities.wsdl is not found

### ISSUE THREAD

**Issue by swathirise123** [epri-dev/CIM-Identities#1]
I followed the process given in manual. When I clicked on "Clean and Build Project" on CIMIdentities-w in NetBeans 8.2, I got the following error
[ERROR] file:/C:/Users/swath/CIM-Identities-master/CIMIdentities-w/src/conf/xml-resources/web-services/CIMIdentities/wsdl/Send_Receive_Reply_CIMIdentities.wsdl is unreachable

Where can I find that wsdl file?  How to build project successfully?

**Comment by DanielRLowe** [comment]
This is odd because I just redownloaded the zip file to reinstall and was able to build without issue by going through the instructions.  Can you confirm that the path you listed above is actually the correct path and that the file indeed is missing?  I never had to do anything to change the path, but it seems like it should actually be looking in Documents but isn't?  (For reference, when I tested, I unzipped this straight to C:// and opened the project from there).

Edit:  Apparently I had loaded the wrong version.  I was able to recreate the issue using the one in the zip file and will see what's going on and get back to you!

**Comment by swathirise123** [comment]
Thank you for replying to my issue. Should I unzip it straight to C:// or Documents?

**Comment by DanielRLowe** [comment]
@swathirise123  Nope, you can unzip it wherever you like.  The issue wasn't the pathname.  Rather, if you checked the path you'll see that the file isn't actually there.  Something got lost in the transition between my working release a while back and another that was uploaded to replace it.  The missing files have been replaced in the latest version, so redownload it and you shouldn't have an issue.  Just pay attention to error messages in case you come across something a bit different from what I might have brought up in the guide.  

I've tested that the new version (really it's the old version if you want to be technical) works as expected, so give it a go and if you encounter any issues, open up a new issue as I'll consider this one now closed.  Thanks for the heads up.

**Comment by swathirise123** [comment]
Thank you so much. I will try and if I have problem, I'll get back to you.
